# Site settings
title: Chitranjali
description: My site
#baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for  your site e.g. http://willianjusten.com.br

# User settings
username: Chitranjali Edpuganti
user_description: Hi There! I'm chitra, your average Jane who is serious about her craft..! I am  currently working as a Software Developer, A Pythonista and a certified AWS developer, Apart from this my interests include Movies, Fitness, Fashion, Nutrition, Cooking, landscaping.
user_title: Software Developer
email: chitranjali
twitter_username:
github_username:  chitranjali
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
